### ISSUE TITLE
how to run locally?

### ISSUE THREAD

**Issue by harlantwood** [digitalbazaar/ld-signature-demo#1]
We are considering integrating bitcoin signing of JSON LD here, instead of (or in addition to) here: https://github.com/json-ld/json-ld.org/issues/431 

When trying to start this project, it seems to be looking for a server on `127.0.53.53:18443` -- what is it expecting to find there?

```
$ node -v
v6.9.1
$ npm start

> ld-signature-demo@0.1.0-dev start [...]/ld-signature-demo
> node signing-demo-dev.js

2016-11-16T23:43:45.233Z - info: starting bedrock...
2016-11-16T23:43:45.249Z - info: running bedrock master process "bedrock1d" pid=95425
2016-11-16T23:43:46.404Z - info: running bedrock worker process "bedrock1d-worker" workerPid=95426
2016-11-16T23:43:46.422Z - debug: starting HTTPS server on bedrock.dev:18443 workerPid=95426
2016-11-16T23:43:46.422Z - debug: starting HTTP server on bedrock.dev:18080 workerPid=95426
2016-11-16T23:43:46.498Z - critical: worker: uncaught error: Error: bind EADDRNOTAVAIL 127.0.53.53:18443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at cb (net.js:1322:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) workerPid=95426
2016-11-16T23:43:46.508Z - critical: worker 95426 exited with code 1
```

**Comment by harlantwood** [comment]
I'm on the `implementation` branch ( as you would likely guess : )

**Comment by harlantwood** [comment]
OK, I solved it.  I had to:
1. add to my `/etc/hosts` the line: `127.0.0.1  bedrock.dev`
2. install and start mongodb

Works now 👍

**Comment by harlantwood** [comment]
added basic dev setup docs PR: #2
